"""Facebook个人养号SOP参考数据 — 来自 Notion SOP 文档"""

SOP_REFERENCE = [
    {
        "day": 0,
        "title": "📋 开始前准备（第0天）",
        "color": "gray",
        "sections": [
            {
                "subtitle": "🛍️ 账号选购",
                "items": [
                    "优先选购申请时长 ≥1年、有发帖记录、有过电话验证的老号",
                    "新号3天内属高危期，1周内基本安全，2周后完全适应新环境",
                    "养号总周期：最短2周，最优1个月",
                    "确认账号绑定的邮箱可正常访问",
                ],
            },
            {
                "subtitle": "🖥️ 环境准备",
                "items": [
                    "配置指纹浏览器（比特浏览器），每个账号独立环境，绝不混用",
                    "配置住宅代理IP（Residential IP），确保IP地区与FB账号注册地区、BM地区三者一致",
                    "❌ 封过号的环境与IP永久弃用",
                    "❌ 同一环境禁止同时登录两个个人号",
                ],
            },
            {
                "subtitle": "⚠️ 核心注意",
                "items": [
                    "FB个号 / BM / 住宅代理IP 三者地区必须一致",
                    "个人资料越完善越好，直接影响投放稳定性",
                    "不要更改FB语言（触发异常登录检测）",
                ],
            },
        ],
    },
    {
        "day": 1,
        "title": "🟡 第1天",
        "color": "yellow",
        "once": ["首次登录新环境，如出现验证联系号商处理"],
        "daily": ["只浏览 Feed，不点赞、不评论、不操作任何功能"],
        "forbidden": ["不修改任何账户配置（语言、密码、邮箱等）"],
        "time": "30–60 min",
    },
    {
        "day": 2,
        "title": "🟡 第2天",
        "color": "yellow",
        "once": ["将个人资料可见性改为「仅好友」"],
        "daily": ["浏览 Feed + 点赞 ≤5"],
        "forbidden": ["不做BM/主页操作", "不加好友"],
        "time": "30–120 min",
    },
    {
        "day": 3,
        "title": "🟡 第3天",
        "color": "yellow",
        "once": ["上传头像 + 封面照片", "OAuth: Canva"],
        "daily": [
            "Feed 点赞 ≤8 + 转发 ≤2",
            "Reels 10min（每条≥30s）点赞 ≤3",
            "加好友 5–8（加前先浏览主页+点赞）",
        ],
        "time": "30–120 min",
    },
    {
        "day": 4,
        "title": "🟡 第4天",
        "color": "yellow",
        "once": ["填现居城市（与代理IP地区一致）", "OAuth: Change.org"],
        "daily": ["Feed + Reels + Stories 3–5条", "加好友 5–8"],
        "time": "30–120 min",
    },
    {
        "day": 5,
        "title": "🟡 第5天",
        "color": "yellow",
        "once": ["填家乡（与现居城市同国）", "注册 Instagram 并关联FB", "开启双重验证（Google Authenticator）"],
        "daily": ["Feed + Reels + Stories", "加好友 5–8"],
        "time": "30–120 min",
    },
    {
        "day": 6,
        "title": "🟡 第6天",
        "color": "yellow",
        "once": [
            "填生日（25–40岁区间）",
            "增加信任联系人",
            "下载账号副本",
            "OAuth: Spotify",
            "加入 2–3 个目标受众群组",
        ],
        "daily": ["Feed 点赞 ≤15 + 转发 ≤3", "Reels 点赞 ≤5", "Stories 3–5条", "加好友 5–8"],
        "time": "30–120 min",
    },
    {
        "day": 7,
        "title": "🟠 第7天",
        "color": "orange",
        "once": ["填性别 + 语言"],
        "daily": [
            "Feed 点赞 ≤15 + 转发 ≤3",
            "Reels + Stories",
            "评论好友帖子 1–2条（简短友好，禁广告词）",
            "加好友 5–8",
        ],
        "time": "30–120 min",
    },
    {
        "day": 8,
        "title": "🟠 第8天",
        "color": "orange",
        "once": ["填工作单位（虚构公司名+职位）", "创建粉丝主页 Fanpage", "删除主页快捷链接", "OAuth: Pinterest"],
        "daily": ["同第7天"],
        "time": "30–120 min",
    },
    {
        "day": 9,
        "title": "🟠 第9天 ✋人工",
        "color": "orange",
        "once": ["✋ 填学校（大学名+专业）", "✋ 绑定 BM（地理位置与FB账号一致）", "✋ 创建广告账户（不投放，仅建立，给5天沉淀）"],
        "daily": ["同第7天"],
        "time": "30–120 min",
    },
    {
        "day": 10,
        "title": "🟠 第10天",
        "color": "orange",
        "once": ["填个人简介 Bio", "OAuth: Eventbrite", "BM验证域名", "主页发帖 ≤3条/天（禁广告词与外链）"],
        "daily": ["Feed 点赞 ≤20 + 转发 ≤4", "Reels + Stories", "评论 3–5条", "加好友 5–8"],
        "time": "30–120 min",
    },
    {
        "day": 11,
        "title": "🟠 第11天",
        "color": "orange",
        "once": ["填感情状态 + 网站链接", "粉丝页发一条非广告帖", "安装 Facebook Pixel（配置 Purchase/Lead 事件）"],
        "daily": ["同第10天"],
        "time": "30–120 min",
    },
    {
        "day": 12,
        "title": "🟢 第12天",
        "color": "green",
        "once": ["确认域名 Verified + Pixel 有数据回传"],
        "daily": ["同第10天"],
        "time": "30–120 min",
    },
    {
        "day": 13,
        "title": "🟢 第13天 ✋人工",
        "color": "green",
        "once": ["✋ 检查 BM 额度", "✋ 绑定付款方式（信用卡）"],
        "daily": ["同第10天"],
        "time": "30–120 min",
    },
    {
        "day": 14,
        "title": "🟢 第14天 — 正式投放就绪🚀 ✋人工",
        "color": "green",
        "once": ["✋ 激活广告账户，创建第1个广告系列", "✋ 预算从 $2 起，逐步递增"],
        "daily": ["同第10天，加好友升至 10–20"],
        "warning": "第14天是最低门槛，属投放高风险期。最稳是满30天再投。",
        "time": "30–120 min",
    },
    {
        "day": 15,
        "title": "🔵 第15天+ — 持续投放期日常维护",
        "color": "blue",
        "once": ["✋ 每周检查广告数据（CPM/CTR/CVR/ROAS）", "✋ 递增预算（$2→$10→$25，间隔≥3天）"],
        "daily": ["Feed 点赞 ≤20 + 转发 ≤4", "Reels + Stories", "评论 3–5条", "加好友 10–20", "主页发帖 ≤3条/天"],
        "principle": "投放开始后养号不停。账号活跃度是保护投放额度和降低风控的长期支撑。",
        "time": "30–120 min",
    },
]

HIGH_RISK_BEHAVIORS = [
    {"behavior": "同一环境登录多个账号", "level": "🔴 极高", "note": "立即关联封号"},
    {"behavior": "使用封过号的IP/环境", "level": "🔴 极高", "note": "封号概率极大"},
    {"behavior": "新号直接操作BM/广告", "level": "🔴 极高", "note": "跳过暖号直接触发风控"},
    {"behavior": "频繁切换IP或每次用不同IP登录", "level": "🔴 极高", "note": "触发异常登录检测"},
    {"behavior": "凌晨2:00–5:00活跃", "level": "🟠 高", "note": "与目标地区用户习惯不符"},
    {"behavior": "短时间大量加好友/加群", "level": "🟠 高", "note": "触发反垃圾机制"},
    {"behavior": "发布侵权/虚假/低质内容", "level": "🟠 高", "note": "内容审核触发封号"},
    {"behavior": "FB/BM/IP地区不一致", "level": "🟠 高", "note": "账号可信度大幅下降"},
    {"behavior": "单日连续发帖 ≥5条", "level": "🟠 高", "note": "触发内容威胁检测"},
    {"behavior": "随意修改账户语言/安全设置", "level": "🟡 中", "note": "触发异常登录检测"},
    {"behavior": "广告内容与落地页不一致", "level": "🟡 中", "note": "审核不通过或账户降权"},
]
